"""
UPI-SHIELD dashboard data layer.

This module is responsible only for loading existing project artifacts
and experiment results for the Streamlit dashboard.

No metrics are fabricated here.
No model is trained here.
No prediction is performed here.

All dashboard analytics are sourced from files already generated by
the UPI-SHIELD experimentation pipeline.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Project paths
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parent.parent

RESULTS_DIR = PROJECT_ROOT / "experiments" / "results"
MODELS_DIR = PROJECT_ROOT / "models"


# ---------------------------------------------------------------------------
# Result/configuration paths
# ---------------------------------------------------------------------------

BASELINE_RESULTS_PATH = RESULTS_DIR / "baseline_results.json"

XGBOOST_RESULTS_PATH = RESULTS_DIR / "xgboost_results.json"

COST_THRESHOLD_RESULTS_PATH = (
    RESULTS_DIR / "cost_sensitive_threshold_results.json"
    if (RESULTS_DIR / "cost_sensitive_threshold_results.json").exists()
    else RESULTS_DIR / "cost_aware_results.json"
)

COST_SENSITIVITY_RESULTS_PATH = (
    RESULTS_DIR / "cost_sensitivity_results.json"
)

CALIBRATION_RESULTS_PATH = RESULTS_DIR / "calibration_results.json"

CALIBRATION_TEST_RESULTS_PATH = (
    RESULTS_DIR / "calibration_test_results.json"
)

RISK_SCORING_CONFIG_PATH = (
    MODELS_DIR / "risk_scoring_config.json"
)

DECISION_POLICY_PATH = (
    MODELS_DIR / "decision_policy.json"
)

EXPLANATION_REPORT_PATH = (
    RESULTS_DIR / "explanation_report.json"
)


# ---------------------------------------------------------------------------
# Generic JSON loader
# ---------------------------------------------------------------------------

def _load_json(path: Path) -> dict[str, Any] | list[Any] | None:
    """
    Load a JSON artifact.

    Returns None when the file does not exist or cannot be decoded.
    The dashboard can then show an appropriate missing-file message
    rather than crashing.
    """

    if not path.exists():
        return None

    try:
        with path.open("r", encoding="utf-8") as file:
            return json.load(file)
    except (OSError, json.JSONDecodeError):
        return None


# ---------------------------------------------------------------------------
# Missing-file helper
# ---------------------------------------------------------------------------

def missing_file_notice(
    label: str,
    path: Path,
) -> str:
    """
    Return a user-friendly message for a missing dashboard artifact.
    """

    return (
        f"{label} is not available. "
        f"Expected file: {path}"
    )


# ---------------------------------------------------------------------------
# Baseline model
# ---------------------------------------------------------------------------

def load_baseline_results() -> dict[str, Any] | None:
    """
    Load Logistic Regression baseline experiment results.
    """

    return _load_json(BASELINE_RESULTS_PATH)


# ---------------------------------------------------------------------------
# XGBoost model
# ---------------------------------------------------------------------------

def load_xgboost_results() -> dict[str, Any] | None:
    """
    Load XGBoost experiment results.
    """

    return _load_json(XGBOOST_RESULTS_PATH)


# ---------------------------------------------------------------------------
# Cost-aware threshold optimization
# ---------------------------------------------------------------------------

def load_cost_threshold_results() -> dict[str, Any] | None:
    """
    Load the validation-selected cost-aware threshold results.
    """

    return _load_json(COST_THRESHOLD_RESULTS_PATH)


# ---------------------------------------------------------------------------
# Cost sensitivity analysis
# ---------------------------------------------------------------------------

def load_cost_sensitivity_results() -> (
    dict[str, Any] | list[Any] | None
):
    """
    Load cost-sensitivity experiment results.

    This artifact contains the threshold/cost behavior under different
    false-negative to false-positive cost assumptions.
    """

    return _load_json(COST_SENSITIVITY_RESULTS_PATH)


# ---------------------------------------------------------------------------
# Calibration
# ---------------------------------------------------------------------------

def load_calibration_results() -> dict[str, Any] | None:
    """
    Load validation calibration results.
    """

    return _load_json(CALIBRATION_RESULTS_PATH)


def load_calibration_test_results() -> dict[str, Any] | None:
    """
    Load independent test calibration results.
    """

    return _load_json(CALIBRATION_TEST_RESULTS_PATH)


# ---------------------------------------------------------------------------
# Risk scoring configuration
# ---------------------------------------------------------------------------

def load_risk_scoring_config() -> dict[str, Any] | None:
    """
    Load the deployed risk scoring configuration.
    """

    return _load_json(RISK_SCORING_CONFIG_PATH)


# ---------------------------------------------------------------------------
# Decision policy
# ---------------------------------------------------------------------------

def load_decision_policy() -> dict[str, Any] | None:
    """
    Load the cost-aware decision policy.
    """

    return _load_json(DECISION_POLICY_PATH)


# ---------------------------------------------------------------------------
# Explainability report
# ---------------------------------------------------------------------------

def load_explanation_report() -> dict[str, Any] | None:
    """
    Load the benchmark reference SHAP explanation report.
    """

    return _load_json(EXPLANATION_REPORT_PATH)


# ---------------------------------------------------------------------------
# Artifact availability helpers
# ---------------------------------------------------------------------------

def artifact_exists(path: Path) -> bool:
    """
    Return True when a dashboard artifact exists.
    """

    return path.exists()


def get_artifact_status() -> dict[str, bool]:
    """
    Return availability status for all dashboard artifacts.
    """

    paths = {
        "baseline_results": BASELINE_RESULTS_PATH,
        "xgboost_results": XGBOOST_RESULTS_PATH,
        "cost_threshold_results": COST_THRESHOLD_RESULTS_PATH,
        "cost_sensitivity_results": COST_SENSITIVITY_RESULTS_PATH,
        "calibration_results": CALIBRATION_RESULTS_PATH,
        "calibration_test_results": CALIBRATION_TEST_RESULTS_PATH,
        "risk_scoring_config": RISK_SCORING_CONFIG_PATH,
        "decision_policy": DECISION_POLICY_PATH,
        "explanation_report": EXPLANATION_REPORT_PATH,
    }

    return {
        name: artifact_exists(path)
        for name, path in paths.items()
    }